### ISSUE TITLE
Error using pip to install it.

### ISSUE THREAD

**Issue by ahmed4end** [odashi/latexify_py#11]
ERROR: latexify_py is not a valid editable requirement. It should either be a
th to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+).

**Comment by odashi** [comment]
This library is not uploaded on PyPI currently. You need to clone it directly before installing:
```
$ git clone https://github.com/odashi/latexify_py
$ pip install -e latexify_py
```
