### ISSUE TITLE
Write the latexify object directly to file

### ISSUE THREAD

**Issue by yangc22** [odashi/latexify_py#14]
Hi,
I have a question. When printing the function with the latexify decorator, is there any way that I can use the format string to print the "function" string directly. As I have 10 functions name from "p1" to "p10". Is it possible to write a for loop to print all the functions?
Also, is it possible to directly convert the function to string and write it to a file? Thanks!
Thanks.

**Comment by ryxcommar** [comment]
Do you want to print the rendered latex or the raw (unrendered latex)?

## Rendered LaTeX

Assuming you already decorated the functions:

```python
from IPython.display import display

list_of_funcs = [p1, p2, p3, p4, p5, p6, p7, p8, p9, p10]

for f in list_of_funcs:
    display(f)
```

If not:

```python
from IPython.display import display
from latexify import get_latex

list_of_funcs = [p1, p2, p3, p4, p5, p6, p7, p8, p9, p10]

for f in list_of_funcs:
    display(get_latex(f))
```

## Unrendered latex

Assuming functions were not decorated:

```python
list_of_funcs = [p1, p2, p3, p4, p5, p6, p7, p8, p9, p10]

for f in list_of_funcs:
    print(get_latex(f))
```

**Comment by odashi** [comment]
`get_latex` is the function that directly returns the LaTeX form without modifying the original function. You can also use `str(your_fn)` if you already wrapped your function by `with_latex`.

**Comment by yangc22** [comment]
Thanks for the clarification!
